<a href="https://colab.research.google.com/github/Lincoln-Alyson/atividades-da-aula-de-fundamentos-da-programa-o/blob/main/aula_10_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np_2d= np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [ ]:
np_2d.shape

(2, 5)

In [ ]:
np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,"68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [ ]:
np_3d=np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,68.7],[89.4,45.6,28.4,76.1,43.8]])

In [ ]:
np_3d.shape

(3, 5)

In [ ]:
np_4d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
np_4d.shape

(3, 3)

In [ ]:
np_2d[0]

array(['1.73', '1.68', '1.71', '1.89', '1.79'], dtype='<U32')

In [ ]:
np_2d[0][2]

'1.71'

In [ ]:
np_2d[0,2]

'1.71'

In [ ]:
np_2d[:,1:3]

array([['1.68', '1.71'],
       ['59.2', '63.6']], dtype='<U32')

In [ ]:
np_2d[1,:]

array(['65.4', '59.2', '63.6', '88.4', '68.7'], dtype='<U32')

In [ ]:
baseball=[180,215,210,210,188,176,209,200]

In [ ]:
#1
import numpy as np

In [ ]:
#2
np_baseball=np.array([180,215,210,210,188,176,209,200])

In [ ]:
#3
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [ ]:
#4
np_baseball.shape

(8,)

In [4]:
import random as rd 
import numpy as np 
#geração de numeros entre 150 e 209
height=range(150,210)
print(range(150,210))
#geração de números entre 50 e 149
weight= range(50,150)
print(range(50,150))
#amostra randonica de 20 numeros de height
height=rd.sample(height,20)
print(rd.sample(height,20))
#amostra randomica de 20 numeros de weight
weight=rd.sample(weight,20)
print(rd.sample(weight,20))
#converter height em array e normalizar multiplicando por 0,01
height_array=np.array(height)*0.01
print(height_array)
#converter weight em array
weight_array=np.array(weight)
#calculo do BMI
bmi= weight_array/height_array**2
print(bmi)
#verificação onde bmi é menor que 21
light= bmi<21
#print light
print(light)
#exibição dos valores de bmi com valor menor que 21 
print(bmi[bmi<21])
#print os elementos de weight_array do index 8 ate o index 15, incluindo o index 15
print(weight_array[9:16])
#print os elemntos de height_array do index 11 ate o 19, incluindo o 19
print(height_array[12:20])

range(150, 210)
range(50, 150)
[194, 159, 156, 203, 184, 198, 172, 208, 160, 199, 164, 170, 181, 185, 175, 201, 188, 204, 180, 177]
[139, 137, 114, 98, 68, 146, 134, 136, 62, 96, 149, 71, 147, 131, 133, 89, 122, 115, 86, 138]
[1.98 1.84 1.59 2.03 2.08 1.94 1.99 1.6  1.7  1.72 2.04 1.8  1.85 1.64
 1.77 2.01 1.88 1.56 1.81 1.75]
[22.70176513 18.31285444 58.14643408 27.66385984 19.87795858 39.58975449
 35.10012373 57.03125    47.05882353 38.87236344 31.47827759 41.04938272
 40.02921841 51.30874479 21.70512943 24.25682533 27.16161159 50.13149244
 40.90229236 23.18367347]
[False  True False False  True False False False False False False False
 False False False False False False False False]
[18.31285444 19.87795858]
[115 131 133 137 138  68  98]
[1.85 1.64 1.77 2.01 1.88 1.56 1.81 1.75]


In [ ]:
import numpy as np
baseball=[[180,78.4],[215,102.7],[210,98.5],[188,75.2]]
np_baseball=np.array([[180,78.4],[215,102.7],[210,98.5],[188,75.2]])
print(np_baseball[2])
np_weight_lb=(np_baseball[:,1])
print(np_weight_lb)
print(np_baseball[1,0])
np.median(np_baseball[:,0])
np.median(np_baseball[1])

[210.   98.5]
[ 78.4 102.7  98.5  75.2]
215.0


158.85